### ISSUE TITLE
Join us in the cashshuffle Telegram group

### ISSUE THREAD

**Issue by alwaysAn0n** [bookmoons/cashshufflejs#34]
Hi @bookmoons !  Sorry for using Issues to get your attention.  I didn't know the best way to get in touch.

I'm a dev helping to build out the CashShuffle ecosystem.  On behalf of myself, @zquestz ,   @emergent-reasons , @cculianu , and @fyookball , we would like to welcome you to join us in our private Telegram channel where we coordinate development efforts and discuss ideas on how to best achieve the goals on our roadmap.

We found the feedback you provided in [this reddit post](https://www.reddit.com/r/btc/comments/9ff0sa/establishing_cashshuffle_protocol_details/) to be super insightful.  There are some tough problems ahead of us like shuffled coin consolidation and dust shuffling.  We would love your input.  Please PM me on Telegram so I can add you to our channel.  My Telegram username is `alwaysAn0n` .

Take care!

**Comment by cculianu** [comment]
EC Dev here (worked on CashShuffle too).  

@bookmoons  - Yes, please come join us. We think you did great work here.  You'd love it in our Telegram.

**Comment by bookmoons** [comment]
Thanks a lot guys. It's a good time, I've just been trying to figure out the right way to refresh this. My current approach got too complicated. Will look into the group when I have a chance. The new features sound really interesting.

**Comment by cculianu** [comment]
Just write back here and we can send you an invite link. Maybe if you come to the group you may find some fresh motivation... so don't forget! :D
